name: saabi_mobile
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  kickin_utilities: ^0.0.1-dev.4
  kickin_network: ^0.0.2
  flutter_riverpod: ^3.3.2
  go_router: ^17.3.0

  google_fonts: ^8.1.0
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.0
  forui: ^0.23.0
  lucide_icons_flutter: ^3.1.14+2
  kickin_storage: ^0.0.1
  cached_network_image: ^3.4.1
  path_provider: ^2.1.6
  path: ^1.9.1
  hugeicons_pro: ^0.0.3
  intl: ^0.20.2
  isar_community: 3.3.2
  isar_community_flutter_libs: 3.3.2
  google_mlkit_entity_extraction: ^0.15.3

flutter_gen:
  output: lib/core/assets/
  assets:
    exclude:
      - assets/fonts/**
  # Optional
  integrations:
    image: false

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  build_runner: any
  flutter_gen_runner:
  isar_community_generator: 3.3.2

flutter:
  uses-material-design: true
  
  assets:
   # - assets/images/
